### ISSUE TITLE
Proposed sitemap for 2014 event

### ISSUE THREAD

**Issue by mrconnerton** [drupalasheville/drupalasheville.com#1]
* Sessions
  * Submit a Session
  * Proposed sessions
  * Program
  * Schedule
* Sponsors
  * Become a sponsor
    * https://2014.drupalcampcolorado.org/sponsorships
    * http://2014.midcamp.org/sponsor-midcamp
* Register
* Venue
  * What's Around / Map
  * Lodging
  * Airport / Directions
* Updates
  * News content type (I think there is already a cod feature for this)
* Contact Us (webform)
* Code of Conduct
  * https://2014.drupalcampcolorado.org/content/drupalcamp-colorado-code-conduct-dccococ

**Comment by andyg5000** [comment]
Closing 2014 issues.
