### ISSUE TITLE
Javascript errors on first page load

### ISSUE THREAD

**Issue by daggerhart** [drupalasheville/drupalasheville.com#42]
When viewing a page for the first time, there is a problem with javascript loading on the page.

Ex: http://drupalasheville.com/camp/2015/location  On this page, it is common for the map to not load at all.

I dug into the site a bit and didn't find anything specific at cause.  Currently I suspect it to be Cloudflare / rocketscript related.

**Comment by andyg5000** [comment]
@mrconnerton Can you PM cloudflare credentials to @daggerhart so he can investigate?
