### ISSUE TITLE
setup captcha/spam prevention

### ISSUE THREAD

**Issue by andyg5000** [drupalasheville/drupalasheville.com#45]

**Comment by andyg5000** [comment]
@daggerhart i think you said you'd do this ;) Feel free to re-assign

**Comment by daggerhart** [comment]
sure thing, i'll take care of this over the weekend... one way or another

**Comment by daggerhart** [comment]
I updated honeypot, and install spambot.  Spambot compares new and existing users against a database of reported spammer accounts.  Might be something better, but it seems okay so far.
