### ISSUE TITLE
Mapping / points of interest

### ISSUE THREAD

**Issue by mrconnerton** [drupalasheville/drupalasheville.com#8]
I have put up a foundation for points of interest and mapping on the site. What is left to do off the top of my head:

- [x] Create a panels variant for location node types
- [x] Create a better path auto pattern based on the the og refernece "camps/2014/location/wedge" ?
- [ ] More content on the venue page
- [x] actually create location nodes
- [x] attach taxonomy field to location
- [x] create exposed filter for map based on taxonomy values
- [x] pretty markers for different taxonomies?

**Comment by andyg5000** [comment]
Closing 2014 issues.
